name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/osx_64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman spec lint "f5988249-ec5d-428e-93e5-2a700fcd9ea1" --report-events
          postman collection run "53143593-7c483314-4793-4dec-9230-f58990c5f7d8" -e "53143593-6370a9ae-d483-4c8b-a9bb-2d1f2c1fedfe" --report-events
